### ISSUE TITLE
Bug: Filter command unexpected behaviour

### ISSUE THREAD

**Issue by isaacsaw25** [AY2425S1-CS2113-W12-2/tp#112]
The filter command still shows the unallocated students even if the specified parameter is wrong:
  
![image](https://github.com/user-attachments/assets/e4db060b-0814-4237-a6c9-ef8054adb217)  
  
Perhaps throw an exception if the argument part is wrong? 😅

**Comment by Holy-An** [comment]
Good catch! Will fix now.
