### ISSUE TITLE
[PE-D][Tester E] Invalid Command when Input Absolute Path for File Input

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W12-2/tp#140]
When inputting the initial file path as per given by the User Guide, using the files given by the releases, there is an error in uploading the data leading to the following response:

--------------------------------------------------------------------------------
C:\Users\YK Personal\Desktop\Y2S1\CS2113\PE_dryRun\test.txt
--------------------------------------------------------------------------------
Invalid command
--------------------------------------------------------------------------------
"C:\Users\YK Personal\Desktop\Y2S1\CS2113\PE_dryRun\test.csv"
--------------------------------------------------------------------------------
Invalid command
--------------------------------------------------------------------------------
"C:\Users\YK Personal\Desktop\Y2S1\CS2113\PE_dryRun\test.json"
--------------------------------------------------------------------------------
Invalid command
--------------------------------------------------------------------------------

![image.png](https://raw.githubusercontent.com/yeekian/ped/main/files/4c930e3e-aece-4cda-a586-0d439bf07638.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: yeekian/ped#1

**Comment by isaacsaw25** [comment]
Ok, this is epic. It appears the user is absolutely malding as he can't seem to be able to input his absolute path. 🤣
