### ISSUE TITLE
[PE-D][Tester D] Display Error

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-2/tp#142]
Display error. Should not have ``

![image.png](https://raw.githubusercontent.com/lowjunchen/ped/main/files/9257d63a-1e16-4a45-b916-6f29613b988f.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: lowjunchen/ped#1

**Comment by ehz0ah** [comment]
@Holy-An how?

**Comment by isaacsaw25** [comment]
I'll take this considering it is a valid point. 😢
