### ISSUE TITLE
[PE-D][Tester E] Data lost upon accidental exit

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W12-2/tp#144]
When accidentally press ctrl+c in the terminal, the code exits as expected. However, data input is now lost and needs to be inputted again. This could lead to wasted time in re-entry due to mistakes like this.

![image.png](https://raw.githubusercontent.com/yeekian/ped/main/files/422934c0-6953-4e0b-8505-bf1f7f47a02b.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: yeekian/ped#3

**Comment by ehz0ah** [comment]
I will write it in user guide explicitly to exit only in one way which is through the commands.

**Comment by isaacsaw25** [comment]
Alternatively, you could keep saving the file every time you run `add`, `delete`, `allocate`, revert` etc, so that the file save does not only happen when exiting. Downside to this is the user likely cannot specify the output type and you will just output all formats. 🥇
