### ISSUE TITLE
[PE-D][Tester E] Inconsistent use of tags in Find Command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-2/tp#147]
For 'add' command, the tag 'id/' was used to indicate the STUDENT_ID information. However, the tag is not required for the 'find' command, leading to confusion. It would be good to standardise on the use of tags.

![image.png](https://raw.githubusercontent.com/yeekian/ped/main/files/4d96e790-470b-4c9d-a121-ba5f84ccc1a1.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yeekian/ped#4

**Comment by ehz0ah** [comment]
@Holy-An uty man, give them what they want

**Comment by Holy-An** [comment]
oh nah

**Comment by isaacsaw25** [comment]
@Holy-An Add reject tag
