### ISSUE TITLE
[PE-D][Tester D] Average GPA derived does not match University Granted

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-2/tp#148]
There is only 1 student allocated to University of Liverpool (A4444444A), and that person has a GPA of 4.0. However, for some reason, the average GPA is 4.10? Shouldn't it be updated or reallocated? (Note: Allocate command has been rerun)  

![image.png](https://raw.githubusercontent.com/lowjunchen/ped/main/files/307f6422-0a56-4d0b-bc6b-f81df2f59da8.png)

![image.png](https://raw.githubusercontent.com/lowjunchen/ped/main/files/fbe7e3fc-fcf1-400f-86de-d45c907ee7f9.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: lowjunchen/ped#3

**Comment by ThisisXXZ** [comment]
This is because ``StatCommand`` only display the gpa of students who have **chosen** that specified university. Maybe can update it to the students who are actually allocated to that university

**Comment by isaacsaw25** [comment]
Maybe it would help to be more specific in the user guide? 
> This is because `StatCommand` only display the gpa of students who have **chosen** that specified university. Maybe can update it to the students who are actually allocated to that university  

Alternatively we could change the current behaviour of the stat command.

**Comment by ThisisXXZ** [comment]
I will change the behavior of ``statCommand`` since display the gpa of students who have actually been allocated to the university makes more sense

**Comment by isaacsaw25** [comment]
Fixed in PR #177
