### ISSUE TITLE
[PE-D][Tester E] Unable to load allocation_results.txt into program on start-up

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-2/tp#150]
It would be good to allow the re-input of the allocation_results.txt generated by the app on start-up again. The reason this is beneficial is due to the format at which information in allocation_results.txt is stored, which is not very readable. Allowing the input of the file will allow for the use of the app to display the allocation results again

![image.png](https://raw.githubusercontent.com/yeekian/ped/main/files/38e4f274-cfd7-4d63-921c-cb27dbc60a06.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: yeekian/ped#5

**Comment by ehz0ah** [comment]
gotta make readers understand that results cannot be inputted
