### ISSUE TITLE
[PE-D][Tester B] Inconsistency with User Guide exit commands and actual program

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W12-2/tp#157]
In the UG, it says that when **any of the 3** exit commands are entered..... However, in the very first stage (seen in image), only 'exit' works.

![Screenshot 2024-11-08 at 2.20.15 PM.png](https://raw.githubusercontent.com/andreusxcarvalho/ped/main/files/989a52c8-c621-4b1d-aa80-c61493b1fb6e.png)

![Screenshot 2024-11-08 at 2.21.01 PM.png](https://raw.githubusercontent.com/andreusxcarvalho/ped/main/files/782369a2-4fc4-4315-aad0-cf8f45d193f8.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: andreusxcarvalho/ped#3

**Comment by ehz0ah** [comment]
I will be more robust
