### ISSUE TITLE
BigDecimal or Float

### ISSUE THREAD

**Issue by Holy-An** [AY2425S1-CS2113-W12-2/tp#24]
Hi guys, there is an ongoing discussion on whether we should use BigDecimal or Floats regarding the value of GPA 

 public class Student {
    private String name;
    private int id;
    private float gpa;
}

Although BigDecimal is more precise, it might not be necessary in some cases.
Personally, I would say we can wait for Xing Zhuang to come up with his algorithm first and see if any calculations are required. Using floats are fine for now.
What do you guys think?

**Comment by paulktham** [comment]
I think Xing Zhuang can have the final say as well

**Comment by ThisisXXZ** [comment]
I think float is enough for storing GPA. I will sort GPAs in descending order, so as long as the data type is comparable, the algorithm will work.

**Comment by isaacsaw25** [comment]
I was also thinking of overloading the comparison operators in the 'Student` class, so that we can directly compare `Student` objects.

**Comment by paulktham** [comment]
> I was also thinking of overloading the comparison operators in the `Student` class, so that we can directly compare `Student` objects.

thats a good idea as well
