### ISSUE TITLE
Discussion On How To Implement v2.0 New Features

### ISSUE THREAD

**Issue by ThisisXXZ** [AY2425S1-CS2113-W12-2/tp#51]
Here are the two additional features I'm going to implement in version 2.0:
1. access the average GPA and min GPA of the students who chose the partner university
2. view the availability of university spots

Since we already got a compact and simple instruction set, do you think I should add more commands for these new features?

What I have in mind is intergrating these information into the report we generated, so that we could avoid making our instruction set more complex (we already got 7 commands by now). 

What do you guys think?

**Comment by paulktham** [comment]
My opinion is that the these two features which we are trying to achieve is different from the focus on the report as of now. The report that we are generating now is more of student focused, whereas these things tend to be more university focused. I think it would make more sense if these were commands.

**Comment by paulktham** [comment]
oops misclick above ^

**Comment by ThisisXXZ** [comment]
> My opinion is that the these two features which we are trying to achieve is different from the focus on the report as of now. The report that we are generating now is more of student focused, whereas these things tend to be more university focused. I think it would make more sense if these were commands.

What do you think we should name these two new commands?

**Comment by ehz0ah** [comment]
I agree with Paul. It is also easier for programmers to trace function calls. If it ever gets too messy or has too many commands, we can always refactor commands such as `Add`, `Delete`, `Generate`, etc. to a single command like `ActionCommand` in the future.

**Comment by isaacsaw25** [comment]
Some ideas for getting statistics:
- To view the average GPA and min GPA of the students who chose the partner university

1. `stats -gpamax <UNI_INDEX>`
2. `stats -gpamin <UNI_INDEX>`

- To view the availability of university spots
`viewRemainingQuota <UNI_INDEX>`

**Comment by ThisisXXZ** [comment]
Marked as done. Will link this issue to my PR
