### ISSUE TITLE
Adding GPA criteria function

### ISSUE THREAD

**Issue by paulktham** [AY2425S1-CS2113-W12-2/tp#52]
This required me to adjust code from the Parser class to the Allocator class

- Implemented new case within the parseInput function in Parser Class
- Created new CriteriaCommand class which runs the setMinimumGPA function
- Created a static double minimumGPA in the allocator class as well as functions to set the variable and to view it
- Changed the function validateGPA in studentList class to be public so we can reuse the code that we have already written
- Created more JUnit Tests to test the new implementation

![Image](https://github.com/user-attachments/assets/fc04bdd1-4c62-433b-9ac4-fc1451113d9d)

- Also added more ways to exit the program for the user. "bye", "quit" are now accepted as a way to quit the CLI app as well

#fix 53

**Comment by isaacsaw25** [comment]
Thanks for implementing the additional methods to quit the app! 😄
