### ISSUE TITLE
Fix ListCommand logic

### ISSUE THREAD

**Issue by isaacsaw25** [AY2425S1-CS2113-W12-2/tp#56]
The `run()` method in `ListCommand` should not be invoking the `printStudentList()` method from the `StudentList` class, instead should call directly the `printStudentList()` method from the UI class by passing in the `ArrayList<Student>`

1. Remove `printStudentList()` from `StudentList`.
2. Create a private reference to `ui` in the ListCommand.
3. Pass in the correct arguments to the UI.

**Comment by paulktham** [comment]
Nice catch Isaac! It is crucial to catch these minor flaws in our design!

**Comment by Holy-An** [comment]
Awesome eagle-eye catch! We should indeed make these changes.
