### ISSUE TITLE
UI Package Implementation

### ISSUE THREAD

**Issue by isaacsaw25** [AY2425S1-CS2113-W12-2/tp#7]
As an administrator, I want to interact the system to execute basic output functions (Hi, Bye, Print Table, and Prompt for Table) so that I can easily view, interact with, and input necessary data.

- [x] Import ASCIITable dependencies into Gradle project
- [x] Implement a generic `println()` function
- [x] Implement basic greeting functions
- [x] Print dummy values to the console table
- [x] Remove old "Duke" greeting code

**Comment by ehz0ah** [comment]
Excited to see your implementation!

**Comment by isaacsaw25** [comment]
> Excited to see your implementation!

![](https://media.tenor.com/TMhnW8cH10gAAAAe/war-meme.png)
